### ISSUE TITLE
Warning about malformed migration names?

### ISSUE THREAD

**Issue by lgmys** [rust-db/refinery#129]
Hey! So, today I stumbled about possible improvement to how migration loading is handled. Currently, when using the sql-files based approach, refinery does not report SQL files in the migrations directory that do not conform to the naming convention. It wont say a word about having something like "V1_name" instead of "V1__proper_name" (bad version prefix). Maybe this is a possible improvement to make?:)

**Comment by jxs** [comment]
Hi!, yeah that has happened before: https://github.com/rust-db/refinery/issues/115, would you like to give it a go?
So i would log a warning here [`find_migration_files`](https://github.com/rust-db/refinery/blob/master/refinery_core/src/util.rs#L48) since all the files on migration dirs should be valid migrations

**Comment by lgmys** [comment]
Sure, I will try it today!

**Comment by lgmys** [comment]
In fact, just did. Kudos!
