### ISSUE TITLE
How to use Migrate, MigrateGroup traits for sqlite?

### ISSUE THREAD

**Issue by bburdette** [rust-db/refinery#29]
I'm getting an error like this:

```
error[E0277]: the trait bound `rusqlite::Connection: refinery::MigrateGrouped<'_>` is not satisfied
  --> src/sqldata.rs:61:24
   |
61 |   migrations::runner().run(&mut conn).map_err(|e| e.into())
   |                        ^^^ the trait `refinery::MigrateGrouped<'_>` is not implemented for `rusqlite::Connection`

error[E0277]: the trait bound `rusqlite::Connection: refinery::Migrate` is not satisfied
  --> src/sqldata.rs:61:24
   |
61 |   migrations::runner().run(&mut conn).map_err(|e| e.into())
   |                        ^^^ the trait `refinery::Migrate` is not implemented for `rusqlite::Connection`

```

What should I do to get these traits into scope for rusqlite::Connection?

In my Cargo.toml I added these (I'm also adding barrel)

```
barrel = { version = "0.6.2", features = ["sqlite3"] }
refinery = { version = "0.1.10", feature = ["rusqlite"] }
```

And in the file where I'm getting the error, I added some new 'use' stmts:

```
use barrel::backend::Sqlite;
use barrel::{types, Migration};
use migrations;
use refinery::embed_migrations;
use refinery::{Migrate, MigrateGrouped};
use rusqlite::{params, Connection};
```

And the actual migration code looks like this:

```
mod embedded {
  use refinery::embed_migrations;
  embed_migrations!("src/migrations");
}

pub fn dbinit(dbfile: &Path) -> Result<(), Box<dyn Error>> {
  let conn = Connection::open(dbfile)?;

  migrations::runner().run(&mut conn).map_err(|e| e.into())
}
```

I have a PR open on this project with all my changes:

https://github.com/bburdette/pdfq/pull/4

**Comment by jxs** [comment]
Hi there. you have a typo on your [Cargo.toml](https://github.com/bburdette/pdfq/blob/2448ad8ad84db4ee2f914f4bac7f3952b7c50d03/server/Cargo.toml#L26) `feature` instead of `features`  that's why the rusqlite feature is not being enabled, you don't need to bring the traits into scope. 
There is an issue though,  in version 0.1.10 of refinery supports rusqlite 0.18, you have 0.20.
 There already an alpha for 0.2: `0.2.0-alpha.2` which supports rusqlite 0.21, if you want to update
thanks!

**Comment by bburdette** [comment]
Ok compiling again!  Thanks for the help.
