### ISSUE TITLE
Automatic Migration Generation

### ISSUE THREAD

**Issue by Immortalin** [rust-db/refinery#4]
Django and other more mature ORMs such as TypeORM can automatically generate migrations based on the data structure. This increases productivity and frees users from having to keep DB layout and code data structures in sync.

In Enterprise settings, there are tooling that take the declarative database management concepts even further for more robust database management: https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-2017

However for simple use cases the Django style automigrations will suffice.

**Comment by spacekookie** [comment]
I have to say right upfront that I think that this is *not* in scope for `refinery`.
First because refinery shouldn't actually generate any migrations, but only run them.
So we could argue that this feature is better suited on [`barrel`](https://github.com/rust-db/barrel) since _it_ actually generates migrations.

But I'd also call it out of scope for `barrel`. 
Realistically this is an ORM feature and neither of these two crates are ORMs.
Not to say that this feature wouldn't be immensely valuable
but I think implementing it as a separate crate,
which only exposes a `proc-macro` that can plug into `barrel`
to generate migrations would be a far better approach.

Because such a crate doesn't exist yet I'm gonna leave this issue open,
to have it as a reminder-issue for another crate
(also to give other people a chance to chime in).

I would love to have this feature in the Rust ecosystem,
but it should be it's own library.

**Comment by Immortalin** [comment]
I am putting it here since it falls under rust-db's purview. Diesel as far as ORMs go is _extremely_ bare bones compared to [what's available in other languages](https://typeorm.io/index.html#/migrations).

**Comment by Immortalin** [comment]
In most mature ecosystems, you don't have to cobble together a bunch of crates to get basic functionality working. Migrations etc. should be a first class feature, not something to be delegated.

**Comment by letscodehu** [comment]
@Immortalin I got your point, I've worked with languages like that... but...  you can always be the first one to create a new crate based on top of barrel and diesel or any other ORM's (with adapters) to implement such a functionality. Who knows, maybe it become popular and proves us wrong. But you can't just pile a bunch of (mostly) unused feature into simple crates like this. It would be unnecessary slow and complex.

**Comment by jxs** [comment]
going to close this one, as it's out of the scope of refinery
