### ISSUE TITLE
add SQLx driver

### ISSUE THREAD

**Issue by jxs** [rust-db/refinery#57]

**Comment by belak** [comment]
At least for now, this is harder than you'd expect for multiple reasons:

- The current API for SQLx does a ping-pong between connection and transaction. When you begin a transaction, it takes ownership of the connection object. This makes writing an `impl AsyncTransaction for sqlx::PgConnection` very hard... it may only be possible with the current APIs/Traits to implement for a PgPool... then the migration system can grab a connection from the pool, and run through the whole process.
- There are compiler bugs around `<Connection as HasRow>::Row vs PgRow` - it has issues inferring that they're the same thing. This can be worked around by using a macro with the concrete types to implement the same functionality everywhere. That may actually be better in the long term. The developer is working on some tweaks which may improve this soon.
- libsqlite-sys has a version mismatch between rusqlite and sqlx. This can be resolved by migrating back to rusqlite 0.22 until sqlx has upgraded.

I may continue this later with Pool rather than the direct Connections if there's still interest.

**Comment by jxs** [comment]
hi, and thanks for looking into this! :+1: 
> The current API for SQLx does a ping-pong between connection and transaction. When you begin a transaction, it takes ownership of the connection object. This makes writing an impl AsyncTransaction for sqlx::PgConnection very hard... it may only be possible with the current APIs/Traits to implement for a PgPool... then the migration system can grab a connection from the pool, and run through the whole process.

that is ok i think, [`mysql_async` support is only implemented for `Pool`](https://github.com/rust-db/refinery/blob/master/refinery_core/src/drivers/mysql_async.rs#L39) at the moment too 
regarding the other two issues, i'd rather wait for sqlx to update to 0.23, and the compiler bugs to be fixed, what do you think?

**Comment by belak** [comment]
I don't know how soon the compiler bugs will be fixed, but I think waiting for a new SQLx version to work around them would be good enough.

One other question: how would the API for this work? I've got the basic driver done but I'm not as sure about the other necessary changes. Since there would be multiple types which could provide migrations for the different database types it complicates things a bit.

**Comment by jxs** [comment]
> I don't know how soon the compiler bugs will be fixed, but I think waiting for a new SQLx version to work around them would be good enough.

ok awesome :+1: 

>One other question: how would the API for this work? I've got the basic driver done but I'm not as sure about the other necessary changes. Since there would be multiple types which could provide migrations for the different database types it complicates things a bit.

I am not sure, but what you are saying is that, through SQLx traits we can't have a unified API for all of their supported drivers?

**Comment by JamesHinshelwood** [comment]
Has anything changed on the status of this issue since these previous comments?

I'm happy to take a look at implementing something if there aren't any blockers..?

**Comment by jxs** [comment]
hi @JamesHinshelwood, have the issues mentioned by @belak on https://github.com/rust-db/refinery/issues/57#issuecomment-628325105 been addressed?

**Comment by thomaseizinger** [comment]
> libsqlite-sys has a version mismatch between rusqlite and sqlx. This can be resolved by migrating back to rusqlite 0.22 until sqlx has upgraded.

This is already resolved in latest SQLx master, however, there is a [big release](https://github.com/launchbadge/sqlx/issues/1163) coming up which seems to change things fundamentally so it might be good to wait for 0.6 to be released.

**Comment by jxs** [comment]
also, since `sqlx` now also offers migration features, this might be redundant no?

**Comment by Andrey36652** [comment]
Hello, I think this is still relevant. If I use sqlx already in a project then it can be considered an overkill to add another driver (tokio-postgres for example) just for migrations support.
Are there any technical reasons why sqlx support coudn't be implemented as per current state of things?

**Comment by jxs** [comment]
Hi, and thanks for the interest! But doesn't `sqlx` offer migrations?

**Comment by Andrey36652** [comment]
It does, but:

- it supports only .sql migrations (does not bother me, but Rust migrations is just a nice to have option)
- you can not change migrations table name and schema - at all https://github.com/launchbadge/sqlx/issues/1835 - total dealbreaker for me
- refinery migrations are more customizable in comparison with sqlx migrations

**Comment by jxs** [comment]
Ok I see, thanks for expanding! As I mentioned on https://github.com/rust-db/refinery/pull/295#issuecomment-1838429822 I don't think it makes sense to add more drivers to this repo, but if you are willing to implement support for sqlx I'd love to include it on the `README.md`
